### ISSUE TITLE
[Question] About the timing to call CheckVMXState

### ISSUE THREAD

**Issue by L1B0** [SinaKarvandi/VMCS-Auditor#1]
Hi, I have met error code 0x7 after executing vmlaunch, so I tried to use VMCS-Auditor to find out the reason.

I call CheckVMXState before executing VMLaunch, and it prints "VMFAIL: VMCS EXEC CTRL: VMX proc-based controls allowed 1-settings", so I check the value of vm->vmexec_ctrls2 and VMX_CHECKS_USE_MSR_VMX_PROCBASED_CTRLS_HI, which are 0x94006172 and 0x401e172. And the difference value 0x90000000 is what I add, means CPU_BASED_CTL2_ENABLE_VMFUNC and CPU_BASED_CTL2_ENABLE_VIRT_EXCEPTION.

I guess the reason of VMX_CHECKS_USE_MSR_VMX_PROCBASED_CTRLS_HI not equal to  vmexec_ctrls2 is the value that I write to msr[VMCS_32BIT_CONTROL_PROCESSOR_BASED_VMEXEC_CONTROLS 0x4002] is not really loaded because of executing CheckVMXState befor VMLaunch.

As well as I think this error is not the real reason causes vmlanuch failed.

Hoping for your answer, thanks!

**Comment by SinaKarvandi** [comment]
Hello,
Thanks for creating this issue.

This project is really, honestly. I don't expect it to work for now.
Just a tip to solve this kind of error (0x7), try to copy & paste the initialization routine of the HyperDbg or any other working hypervisor. When you've reached a stable version that works, then try to apply your own patches to the VMCS. 

It's the best way to solve these kinds of errors.
